#ifndef FE_OBJECT6_H
#define FE_OBJECT6_H

#include "common.h"
#include "field.h"

extern s32  opHandler_EFFECTPLAY2(ScriptContext *context, s32 a1);
extern s32  opHandler_ALLSEVOL(ScriptContext *context);
extern s32  opHandler_ALLSEVOLTRANS(ScriptContext *context);
extern s32  opHandler_ALLSEPOS(ScriptContext *context);
extern s32  opHandler_ALLSEPOSTRANS(ScriptContext *context);
extern s32  opHandler_SEVOL(ScriptContext *context);
extern s32  opHandler_SEVOLTRANS(ScriptContext *context);
extern s32  opHandler_SEPOS(ScriptContext *context);
extern s32  opHandler_SEPOSTRANS(ScriptContext *context);
extern s32  opHandler_SESTOP(ScriptContext *context);
extern s32  opHandler_COUNTERCLOCKWISETURN(ScriptContext *context);
extern s32  opHandler_CLOCKWISETURN2(ScriptContext *context);
extern void func_800B27C4(s32 entityIdx, s32 *sxy, s32 *out);
extern void func_800B2864(Actor *actor, s32 channel, s32 unused2, s32 unused3);
extern s32  opHandler_FOOTSTEP(Actor *actor, s32 a1);
extern s32  opHandler_FOOTSTEPCOPY(Actor *actor);
extern s32  opHandler_FOOTSTEPON(ScriptContext *context);
extern s32  opHandler_FOOTSTEPOFF(ScriptContext *context);
extern s32  opHandler_FOOTSTEPOFFALL(ScriptContext *context);
extern s32  opHandler_FOOTSTEPCUT(Actor *actor);
extern void func_800B2B48(Actor *actor);
extern void func_800B2BA0(Bganime *bganime);
extern void func_800B2D40(Bganime *bganime, s32 a1, s32 a2);
extern s32  opHandler_BGANIME(Bganime *bganime);
extern s32  opHandler_RBGANIME(Bganime *bganime);
extern s32  opHandler_RBGANIMELOOP(Bganime *bganime);
extern s32  opHandler_BGANIMESYNC(Bganime *bganime);
extern s32  opHandler_BGDRAW(Bganime *bganime);
extern s32  opHandler_BGOFF(Bganime *bganime);
extern s32  opHandler_BGANIMESPEED(Bganime *bganime);
extern s32  opHandler_BGANIMEFLAG(Bganime *bganime);
extern s32  opHandler_BGSHADE(Bganime *bganime);
extern s32  opHandler_RBGSHADELOOP(Bganime *bganime);
extern s32  opHandler_BGSHADESTOP(Bganime *bganime);
extern s32  opHandler_BGSHADEOFF(Bganime *bganime);
extern s32  opHandler_SHAKE(ScriptContext *context);
extern s32  opHandler_SHAKEOFF(ScriptContext *context);
extern s32  opHandler_DSCROLL(ScriptContext *context);
extern s32  opHandler_LSCROLL(ScriptContext *context);
extern s32  opHandler_CSCROLL(ScriptContext *context);
extern s32  opHandler_DSCROLLA(ScriptContext *context);
extern s32  opHandler_LSCROLLA(ScriptContext *context);
extern s32  opHandler_CSCROLLA(ScriptContext *context);
extern s32  opHandler_DSCROLLP(ScriptContext *context);
extern s32  opHandler_LSCROLLP(ScriptContext *context);
extern s32  opHandler_CSCROLLP(ScriptContext *context);
extern s32  opHandler_SCROLLSYNC(ScriptContext *context);
extern s32  opHandler_SCROLLSYNC2(ScriptContext *context);
extern s32  opHandler_DSCROLL2(ScriptContext *context);
extern s32  opHandler_LSCROLL2(ScriptContext *context);
extern s32  opHandler_CSCROLL2(ScriptContext *context);
extern s32  opHandler_DSCROLLA2(ScriptContext *context);
extern s32  opHandler_LSCROLLA2(ScriptContext *context);
extern s32  opHandler_CSCROLLA2(ScriptContext *context);
extern s32  opHandler_DSCROLLP2(ScriptContext *context);
extern s32  opHandler_LSCROLLP2(ScriptContext *context);
extern s32  opHandler_CSCROLLP2(ScriptContext *context);
extern s32  opHandler_SCROLLMODE2(ScriptContext *context);
extern s32  opHandler_SCROLLRATIO2(ScriptContext *context);
extern s32  opHandler_DSCROLL3(ScriptContext *context);
extern s32  opHandler_LSCROLL3(ScriptContext *context);
extern s32  opHandler_CSCROLL3(ScriptContext *context);
extern s32  opHandler_BGCLEAR(Bganime *bganime);
extern s32  opHandler_SETTIMER(ScriptContext *context);
extern s32  opHandler_GETTIMER(ScriptContext *context);
extern s32  opHandler_DISPTIMER(ScriptContext *context);
extern s32  opHandler_KILLTIMER(ScriptContext *context);
extern s32  opHandler_SHADETIMER(ScriptContext *context);
extern s32  opHandler_WORLDMAPJUMP(ScriptContext *context);
extern s32  opHandler_SETCAMERA(ScriptContext *context);
extern s32  opHandler_SETDCAMERA(ScriptContext *context);
extern s32  opHandler_PREMAPJUMP(ScriptContext *context);
extern s32  func_800B45CC(Actor *actor);
extern s32  opHandler_MAPJUMP(ScriptContext *context, s32 a1);
extern s32  opHandler_MAPJUMP3(ScriptContext *context, s32 a1);
extern s32  opHandler_DISCJUMP(ScriptContext *context, s32 a1);
extern s32  opHandler_MAPJUMPO(ScriptContext *context);
extern s32  opHandler_MAPJUMPON(ScriptContext *context);
extern s32  opHandler_MAPJUMPOFF(ScriptContext *context);
extern s32  opHandler_MAPFADEOFF(ScriptContext *context);
extern s32  opHandler_MAPFADEON(ScriptContext *context);
extern s32  opHandler_MENUDISABLE(ScriptContext *context);
extern s32  opHandler_MENUENABLE(ScriptContext *context);
extern s32  opHandler_MENUNORMAL(void);
extern s32  opHandler_MENUPHS(ScriptContext *context);
extern s32  opHandler_MENUSHOP(ScriptContext *context);
extern s32  opHandler_MENUNAME(ScriptContext *context);
extern s32  opHandler_MENUTUTO(ScriptContext *context);
extern s32  func_800B4D34(Actor *actor);
extern s32  opHandler_MENUTIPS(ScriptContext *context);
extern s32  opHandler_REST(Actor *actor);
extern s32  opHandler_DYING(Actor *actor);
extern s32  opHandler_SETHP(ScriptContext *context);
extern s32  opHandler_GETHP(ScriptContext *context);
extern s32  opHandler_MENUSAVE(ScriptContext *context);
extern s32  opHandler_SAVEENABLE(ScriptContext *context);
extern void func_800B4F40(void);
extern s32  opHandler_PHSPOWER(ScriptContext *context);
extern s32  opHandler_PHSENABLE(ScriptContext *context);
extern s32  opHandler_ADDMAGIC(ScriptContext *context);
extern s32  opHandler_OP16A(ScriptContext *context);
extern s32  opHandler_ADDITEM(ScriptContext *context);
extern s32  opHandler_ADDGIL(ScriptContext *context);
extern s32  opHandler_ADDPASTGIL(ScriptContext *context);
extern s32  opHandler_ADDSEEDLEVEL(ScriptContext *context);
extern s32  opHandler_GETCARD(ScriptContext *context);
extern s32  opHandler_SETCARD(ScriptContext *context);
extern s32  opHandler_HOWMANYCARD(ScriptContext *context);

#endif
