#ifndef FE_OBJECT6_H
#define FE_OBJECT6_H

#include "common.h"
#include "field.h"

extern s32  opHandler_EFFECTPLAY2(Actor *eline, s32 a1);
extern s32  opHandler_ALLSEVOL(Actor *eline);
extern s32  opHandler_ALLSEVOLTRANS(Actor *eline);
extern s32  opHandler_ALLSEPOS(Actor *eline);
extern s32  opHandler_ALLSEPOSTRANS(Actor *eline);
extern s32  opHandler_SEVOL(Actor *eline);
extern s32  opHandler_SEVOLTRANS(Actor *eline);
extern s32  opHandler_SEPOS(Actor *eline);
extern s32  opHandler_SEPOSTRANS(Actor *eline);
extern s32  opHandler_SESTOP(Actor *eline);
extern s32  opHandler_COUNTERCLOCKWISETURN(Actor *eline);
extern s32  opHandler_CLOCKWISETURN2(Actor *eline);
extern void func_800B27C4(s32 entityIdx, s32 *sxy, s32 *out);
extern void func_800B2864(Actor *eline, s32 channel, s32 unused2, s32 unused3);
extern s32  opHandler_FOOTSTEP(Actor *eline, s32 a1);
extern s32  opHandler_FOOTSTEPCOPY(Actor *eline);
extern s32  opHandler_FOOTSTEPON(Actor *eline);
extern s32  opHandler_FOOTSTEPOFF(Actor *eline);
extern s32  opHandler_FOOTSTEPOFFALL(Actor *eline);
extern s32  opHandler_FOOTSTEPCUT(Actor *eline);
extern void func_800B2B48(Actor *eline);
extern void func_800B2BA0(FieldEntity *e);
extern void func_800B2D40(Actor *eline, s32 a1, s32 a2);
extern s32  opHandler_BGANIME(Actor *eline);
extern s32  opHandler_RBGANIME(Actor *eline);
extern s32  opHandler_RBGANIMELOOP(Actor *eline);
extern s32  opHandler_BGANIMESYNC(Actor *eline);
extern s32  opHandler_BGDRAW(Actor *eline);
extern s32  opHandler_BGOFF(Actor *eline);
extern s32  opHandler_BGANIMESPEED(Actor *eline);
extern s32  opHandler_BGANIMEFLAG(Actor *eline);
extern s32  opHandler_BGSHADE(Actor *eline);
extern s32  opHandler_RBGSHADELOOP(Actor *eline);
extern s32  opHandler_BGSHADESTOP(Actor *eline);
extern s32  opHandler_BGSHADEOFF(Actor *eline);
extern s32  opHandler_SHAKE(Actor *eline);
extern s32  opHandler_SHAKEOFF(Actor *eline);
extern s32  opHandler_DSCROLL(Actor *eline);
extern s32  opHandler_LSCROLL(Actor *eline);
extern s32  opHandler_CSCROLL(Actor *eline);
extern s32  opHandler_DSCROLLA(Actor *eline);
extern s32  opHandler_LSCROLLA(Actor *eline);
extern s32  opHandler_CSCROLLA(Actor *eline);
extern s32  opHandler_DSCROLLP(Actor *eline);
extern s32  opHandler_LSCROLLP(Actor *eline);
extern s32  opHandler_CSCROLLP(Actor *eline);
extern s32  opHandler_SCROLLSYNC(Actor *eline);
extern s32  opHandler_SCROLLSYNC2(Actor *eline);
extern s32  opHandler_DSCROLL2(Actor *eline);
extern s32  opHandler_LSCROLL2(Actor *eline);
extern s32  opHandler_CSCROLL2(Actor *eline);
extern s32  opHandler_DSCROLLA2(Actor *eline);
extern s32  opHandler_LSCROLLA2(Actor *eline);
extern s32  opHandler_CSCROLLA2(Actor *eline);
extern s32  opHandler_DSCROLLP2(Actor *eline);
extern s32  opHandler_LSCROLLP2(Actor *eline);
extern s32  opHandler_CSCROLLP2(Actor *eline);
extern s32  opHandler_SCROLLMODE2(Actor *eline);
extern s32  opHandler_SCROLLRATIO2(Actor *eline);
extern s32  opHandler_DSCROLL3(Actor *eline);
extern s32  opHandler_LSCROLL3(Actor *eline);
extern s32  opHandler_CSCROLL3(Actor *eline);
extern s32  opHandler_BGCLEAR(Actor *eline);
extern s32  opHandler_SETTIMER(Actor *eline);
extern s32  opHandler_GETTIMER(Actor *eline);
extern s32  opHandler_DISPTIMER(Actor *eline);
extern s32  opHandler_KILLTIMER(Actor *eline);
extern s32  opHandler_SHADETIMER(Actor *eline);
extern s32  opHandler_WORLDMAPJUMP(Actor *eline);
extern s32  opHandler_SETCAMERA(Actor *eline);
extern s32  opHandler_SETDCAMERA(Actor *eline);
extern s32  opHandler_PREMAPJUMP(Actor *eline);
extern s32  func_800B45CC(Actor *eline);
extern s32  opHandler_MAPJUMP(Actor *eline, s32 a1);
extern s32  opHandler_MAPJUMP3(Actor *eline, s32 a1);
extern s32  opHandler_DISCJUMP(Actor *eline, s32 a1);
extern s32  opHandler_MAPJUMPO(Actor *eline);
extern s32  opHandler_MAPJUMPON(Actor *eline);
extern s32  opHandler_MAPJUMPOFF(Actor *eline);
extern s32  opHandler_MAPFADEOFF(Actor *eline);
extern s32  opHandler_MAPFADEON(Actor *eline);
extern s32  opHandler_MENUDISABLE(Actor *eline);
extern s32  opHandler_MENUENABLE(Actor *eline);
extern s32  opHandler_MENUNORMAL(void);
extern s32  opHandler_MENUPHS(Actor *eline);
extern s32  opHandler_MENUSHOP(Actor *eline);
extern s32  opHandler_MENUNAME(Actor *eline);
extern s32  opHandler_MENUTUTO(Actor *eline);
extern s32  func_800B4D34(Actor *eline);
extern s32  opHandler_MENUTIPS(Actor *eline);
extern s32  opHandler_REST(Actor *eline);
extern s32  opHandler_DYING(Actor *eline);
extern s32  opHandler_SETHP(Actor *eline);
extern s32  opHandler_GETHP(Actor *eline);
extern s32  opHandler_MENUSAVE(Actor *eline);
extern s32  opHandler_SAVEENABLE(Actor *eline);
extern void func_800B4F40(void);
extern s32  opHandler_PHSPOWER(Actor *eline);
extern s32  opHandler_PHSENABLE(Actor *eline);
extern s32  opHandler_ADDMAGIC(Actor *eline);
extern s32  opHandler_OP16A(Actor *eline);
extern s32  opHandler_ADDITEM(Actor *eline);
extern s32  opHandler_ADDGIL(Actor *eline);
extern s32  opHandler_ADDPASTGIL(Actor *eline);
extern s32  opHandler_ADDSEEDLEVEL(Actor *eline);
extern s32  opHandler_GETCARD(Actor *eline);
extern s32  opHandler_SETCARD(Actor *eline);
extern s32  opHandler_HOWMANYCARD(Actor *eline);

#endif
