#ifndef FE_OBJECT6_H
#define FE_OBJECT6_H

#include "common.h"
#include "field.h"

extern s32  opHandler_EFFECTPLAY2(Eline *eline, s32 a1);
extern s32  opHandler_ALLSEVOL(Eline *eline);
extern s32  opHandler_ALLSEVOLTRANS(Eline *eline);
extern s32  opHandler_ALLSEPOS(Eline *eline);
extern s32  opHandler_ALLSEPOSTRANS(Eline *eline);
extern s32  opHandler_SEVOL(Eline *eline);
extern s32  opHandler_SEVOLTRANS(Eline *eline);
extern s32  opHandler_SEPOS(Eline *eline);
extern s32  opHandler_SEPOSTRANS(Eline *eline);
extern s32  opHandler_SESTOP(Eline *eline);
extern s32  opHandler_COUNTERCLOCKWISETURN(Eline *eline);
extern s32  opHandler_CLOCKWISETURN2(Eline *eline);
extern void func_800B27C4(s32 entityIdx, s32 *sxy, s32 *out);
extern void func_800B2864(Eline *eline, s32 channel, s32 unused2, s32 unused3);
extern s32  opHandler_FOOTSTEP(Eline *eline, s32 a1);
extern s32  opHandler_FOOTSTEPCOPY(Eline *eline);
extern s32  opHandler_FOOTSTEPON(Eline *eline);
extern s32  opHandler_FOOTSTEPOFF(Eline *eline);
extern s32  opHandler_FOOTSTEPOFFALL(Eline *eline);
extern s32  opHandler_FOOTSTEPCUT(Eline *eline);
extern void func_800B2B48(Eline *eline);
extern void func_800B2BA0(FieldEntity *e);
extern void func_800B2D40(Eline *eline, s32 a1, s32 a2);
extern s32  opHandler_BGANIME(Eline *eline);
extern s32  opHandler_RBGANIME(Eline *eline);
extern s32  opHandler_RBGANIMELOOP(Eline *eline);
extern s32  opHandler_BGANIMESYNC(Eline *eline);
extern s32  opHandler_BGDRAW(Eline *eline);
extern s32  opHandler_BGOFF(Eline *eline);
extern s32  opHandler_BGANIMESPEED(Eline *eline);
extern s32  opHandler_BGANIMEFLAG(Eline *eline);
extern s32  opHandler_BGSHADE(Eline *eline);
extern s32  opHandler_RBGSHADELOOP(Eline *eline);
extern s32  opHandler_BGSHADESTOP(Eline *eline);
extern s32  opHandler_BGSHADEOFF(Eline *eline);
extern s32  opHandler_SHAKE(Eline *eline);
extern s32  opHandler_SHAKEOFF(Eline *eline);
extern s32  opHandler_DSCROLL(Eline *eline);
extern s32  opHandler_LSCROLL(Eline *eline);
extern s32  opHandler_CSCROLL(Eline *eline);
extern s32  opHandler_DSCROLLA(Eline *eline);
extern s32  opHandler_LSCROLLA(Eline *eline);
extern s32  opHandler_CSCROLLA(Eline *eline);
extern s32  opHandler_DSCROLLP(Eline *eline);
extern s32  opHandler_LSCROLLP(Eline *eline);
extern s32  opHandler_CSCROLLP(Eline *eline);
extern s32  opHandler_SCROLLSYNC(Eline *eline);
extern s32  opHandler_SCROLLSYNC2(Eline *eline);
extern s32  opHandler_DSCROLL2(Eline *eline);
extern s32  opHandler_LSCROLL2(Eline *eline);
extern s32  opHandler_CSCROLL2(Eline *eline);
extern s32  opHandler_DSCROLLA2(Eline *eline);
extern s32  opHandler_LSCROLLA2(Eline *eline);
extern s32  opHandler_CSCROLLA2(Eline *eline);
extern s32  opHandler_DSCROLLP2(Eline *eline);
extern s32  opHandler_LSCROLLP2(Eline *eline);
extern s32  opHandler_CSCROLLP2(Eline *eline);
extern s32  opHandler_SCROLLMODE2(Eline *eline);
extern s32  opHandler_SCROLLRATIO2(Eline *eline);
extern s32  opHandler_DSCROLL3(Eline *eline);
extern s32  opHandler_LSCROLL3(Eline *eline);
extern s32  opHandler_CSCROLL3(Eline *eline);
extern s32  opHandler_BGCLEAR(Eline *eline);
extern s32  opHandler_SETTIMER(Eline *eline);
extern s32  opHandler_GETTIMER(Eline *eline);
extern s32  opHandler_DISPTIMER(Eline *eline);
extern s32  opHandler_KILLTIMER(Eline *eline);
extern s32  opHandler_SHADETIMER(Eline *eline);
extern s32  opHandler_WORLDMAPJUMP(Eline *eline);
extern s32  opHandler_SETCAMERA(Eline *eline);
extern s32  opHandler_SETDCAMERA(Eline *eline);
extern s32  opHandler_PREMAPJUMP(Eline *eline);
extern s32  func_800B45CC(Eline *eline);
extern s32  opHandler_MAPJUMP(Eline *eline, s32 a1);
extern s32  opHandler_MAPJUMP3(Eline *eline, s32 a1);
extern s32  opHandler_DISCJUMP(Eline *eline, s32 a1);
extern s32  opHandler_MAPJUMPO(Eline *eline);
extern s32  opHandler_MAPJUMPON(Eline *eline);
extern s32  opHandler_MAPJUMPOFF(Eline *eline);
extern s32  opHandler_MAPFADEOFF(Eline *eline);
extern s32  opHandler_MAPFADEON(Eline *eline);
extern s32  opHandler_MENUDISABLE(Eline *eline);
extern s32  opHandler_MENUENABLE(Eline *eline);
extern s32  opHandler_MENUNORMAL(void);
extern s32  opHandler_MENUPHS(Eline *eline);
extern s32  opHandler_MENUSHOP(Eline *eline);
extern s32  opHandler_MENUNAME(Eline *eline);
extern s32  opHandler_MENUTUTO(Eline *eline);
extern s32  func_800B4D34(Eline *eline);
extern s32  opHandler_MENUTIPS(Eline *eline);
extern s32  opHandler_REST(Eline *eline);
extern s32  opHandler_DYING(Eline *eline);
extern s32  opHandler_SETHP(Eline *eline);
extern s32  opHandler_GETHP(Eline *eline);
extern s32  opHandler_MENUSAVE(Eline *eline);
extern s32  opHandler_SAVEENABLE(Eline *eline);
extern void func_800B4F40(void);
extern s32  opHandler_PHSPOWER(Eline *eline);
extern s32  opHandler_PHSENABLE(Eline *eline);
extern s32  opHandler_ADDMAGIC(Eline *eline);
extern s32  func_800B5134(Eline *eline);
extern s32  opHandler_ADDITEM(Eline *eline);
extern s32  opHandler_ADDGIL(Eline *eline);
extern s32  opHandler_ADDPASTGIL(Eline *eline);
extern s32  opHandler_ADDSEEDLEVEL(Eline *eline);
extern s32  opHandler_GETCARD(Eline *eline);
extern s32  opHandler_SETCARD(Eline *eline);
extern s32  opHandler_HOWMANYCARD(Eline *eline);

#endif
