#ifndef FE_OBJECT4_H
#define FE_OBJECT4_H

#include "common.h"
#include "field.h"

extern void func_800ADB68(u8 *buf, s32 arg);
extern void func_800ADC04(void);
extern s32  opHandler_NOP(Actor *actor);
extern void opHandler_ADD(Actor *actor);
extern void opHandler_SUB(Actor *actor);
extern void opHandler_NEG(Actor *actor);
extern void opHandler_MUL(Actor *actor);
extern void opHandler_DIV(Actor *actor);
extern void opHandler_MOD(Actor *actor);
extern void opHandler_EQ(Actor *actor);
extern void opHandler_GT(Actor *actor);
extern void opHandler_GE(Actor *actor);
extern void opHandler_LT(Actor *actor);
extern void opHandler_LE(Actor *actor);
extern void opHandler_NE(Actor *actor);
extern void opHandler_AND(Actor *actor);
extern void opHandler_OR(Actor *actor);
extern void opHandler_EOR(Actor *actor);
extern void opHandler_NOT(Actor *actor);
extern void opHandler_RSH(Actor *actor);
extern void opHandler_LSH(Actor *actor);
extern s32  opHandler_CAL(Actor *actor, s32 opcode);
extern s32  opHandler_JMP(Actor *actor, s32 a1);
extern s32  opHandler_JPF(Actor *actor, s32 a1);
extern s32  opHandler_GJMP(Actor *actor, s32 a1);
extern s32  opHandler_LBL(Actor *actor, s32 a1);
extern void func_800AE184(Actor *actor);
extern s32  opHandler_RET(Actor *actor, s32 a1);
extern s32  func_800AE3A4(s32 value, s32 mode);
extern s32  opHandler_PSHN_L(Actor *actor, s32 a1);
extern s32  opHandler_PSHI_L(Actor *actor, s32 a1);
extern s32  opHandler_PSHM_B(Actor *actor, s32 a1);
extern s32  opHandler_PSHM_W(Actor *actor, s32 a1);
extern s32  opHandler_PSHM_L(Actor *actor, s32 a1);
extern s32  opHandler_PSHSM_B(Actor *actor, s32 a1);
extern s32  opHandler_PSHSM_W(Actor *actor, s32 a1);
extern s32  opHandler_PSHSM_L(Actor *actor, s32 a1);
extern s32  opHandler_POPI_L(Actor *actor, s32 a1);
extern s32  opHandler_POPM_B(Actor *actor, s32 a1);
extern s32  opHandler_POPM_W(Actor *actor, s32 a1);
extern s32  opHandler_POPM_L(Actor *actor, s32 a1);
extern s32  opHandler_PSHAC(Actor *actor, s32 a1);
extern s32  func_800AE8B4(Actor *actor, u8 newGroup, u16 pcIdx);
extern s32  opHandler_REQ(Actor *actor, s32 a1);
extern s32  opHandler_REQSW(Actor *actor, s32 a1);
extern s32  opHandler_REQEW(Actor *actor, s32 a1);
extern s32  opHandler_PREQ(Actor *actor, s32 a1);
extern s32  opHandler_PREQSW(Actor *actor, s32 a1);
extern s32  opHandler_PREQEW(Actor *actor, s32 a1);
extern s32  opHandler_DEBUG(Actor *actor);
extern s32  opHandler_HALT(Actor *actor);
extern s32  opHandler_SET(Actor *actor, s32 a1);
extern s32  opHandler_SET3(Actor *actor, s32 a1);
extern s32  opHandler_IDLOCK(Actor *actor, s32 bit);
extern s32  opHandler_IDUNLOCK(Actor *actor, s32 bit);
extern s32  opHandler_WAIT(Actor *actor);
extern s32  opHandler_CLEAR(void);
extern s32  opHandler_RND(ScriptContext *context);
extern s32  opHandler_SETMODEL(Actor *actor, s32 a1);
extern s32  opHandler_SETDRESS(Actor *actor);
extern s32  opHandler_GETDRESS(Actor *actor);
extern s32  opHandler_BASEANIME(Actor *actor, s32 a1);
extern s32  opHandler_LADDERANIME(Actor *actor, s32 a1);
extern s32  opHandler_KEYSCAN(Actor *actor);
extern s32  opHandler_KEYON(Actor *actor);
extern s32  opHandler_KEYSCAN2(Actor *actor);
extern s32  opHandler_KEYON2(Actor *actor);
extern s32  opHandler_SARALYOFF(Actor *actor);
extern s32  opHandler_SARALYON();
extern s32  opHandler_SARALYDISPOFF(void);
extern s32  opHandler_SARALYDISPON(void);
extern s32  opHandler_SETLINE(Actor *actor);
extern s32  opHandler_LINEON(Actor *actor);
extern s32  opHandler_LINEOFF(Actor *actor);
extern s32  opHandler_DOORLINEON(Actor *actor);
extern s32  opHandler_DOORLINEOFF(Actor *actor);
extern s32  opHandler_USE(Actor *actor);
extern s32  opHandler_UNUSE(Actor *actor);
extern s32  opHandler_UCON(void);
extern s32  opHandler_UCOFF(void);
extern s32  opHandler_KEY(Actor *actor);
extern s32  opHandler_SETPC(Actor *actor);
extern s32  opHandler_ADDPARTY(Actor *actor);
extern s32  opHandler_SUBPARTY(Actor *actor);
extern s32  opHandler_CHANGEPARTY(Actor *actor);
extern s32  opHandler_SETPARTY(Actor *actor);
extern s32  opHandler_REFRESHPARTY(Actor *actor);
extern s32  opHandler_ISPARTY(Actor *actor);
extern s32  opHandler_GETPARTY(Actor *actor);
extern s32  opHandler_ADDMEMBER(Actor *actor);
extern s32  opHandler_SUBMEMBER(Actor *actor);
extern s32  opHandler_ISMEMBER(Actor *actor);
extern s32  opHandler_SETPARTY2(Actor *actor, s32 a1);
extern s32  opHandler_SWAP(Actor *actor);
extern s32  opHandler_LASTIN(Actor *actor, s32 a1);
extern s32  opHandler_LASTOUT(Actor *actor);

#endif
